/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    TestComponent: typeof import('./../components/TestComponent.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UForm: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UiFormFormControl: typeof import('./../components/ui/form/FormControl.vue')['default']
    UiFormFormDescription: typeof import('./../components/ui/form/FormDescription.vue')['default']
    UiFormFormItem: typeof import('./../components/ui/form/FormItem.vue')['default']
    UiFormFormLabel: typeof import('./../components/ui/form/FormLabel.vue')['default']
    UiFormFormMessage: typeof import('./../components/ui/form/FormMessage.vue')['default']
    UiLabelLabel: typeof import('./../components/ui/label/Label.vue')['default']
    UInput: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UiTableTable: typeof import('./../components/ui/table/Table.vue')['default']
    UiTableTableBody: typeof import('./../components/ui/table/TableBody.vue')['default']
    UiTableTableCaption: typeof import('./../components/ui/table/TableCaption.vue')['default']
    UiTableTableCell: typeof import('./../components/ui/table/TableCell.vue')['default']
    UiTableTableEmpty: typeof import('./../components/ui/table/TableEmpty.vue')['default']
    UiTableTableFooter: typeof import('./../components/ui/table/TableFooter.vue')['default']
    UiTableTableHead: typeof import('./../components/ui/table/TableHead.vue')['default']
    UiTableTableHeader: typeof import('./../components/ui/table/TableHeader.vue')['default']
    UiTableTableRow: typeof import('./../components/ui/table/TableRow.vue')['default']
    UiTextareaTextarea: typeof import('./../components/ui/textarea/Textarea.vue')['default']
    USelect: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTextarea: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
